declare let x: Promise<any>;
async function foo() {
    return await x;
           ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
}
(async () => await x);
             ~~~~~     [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]

async function avoidDuplicateErrorsCausedByComments() {
    return ( // return await
        await x
        ~~~~~   [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
    );
    return /* => await */ await x;
                          ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
}
async function allowTypeAssertion() {
    return (await x)!;
    return (await x as number);
    return <string> await x;
}
async function allowedInsideTryCatch() {
    try {
        return await x;
    } catch (e) {
        // handle error
        return await x; // not allowed in catch when there is no finally
               ~~~~~                                                     [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
    }
}
async function allowedInsideTryFinally() {
    try {
        return await x;
    } finally {
        // do cleanup, close connection for example
        return await x; // not allowed in finally at all
               ~~~~~                                     [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
    }
}
async function allowedInsideCatchFinally() {
    try {
        return await x;
    } catch (e) {
        return await x;
    } finally {
        return await x;
               ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
    }
}
async function nestedTryStatements() {
    try {
        try {
            return await x;
        } catch (e) {
            return await x;
        } finally {
            return await x;
        }
    } catch(e) {
        try {
            return await x;
        } catch (e) {
            return await x;
        } finally {
            return await x;
        }
    } finally {
        try {
            return await x;
        } catch (e) {
            return await x;
        } finally {
            return await x;
                   ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
        }
    }
}

async function handleParens() {
    return (await x);
            ~~~~~     [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
}
async function handleBinaryExpression() {
    return await foo() || await x;
                          ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
    return await foo() && await x;
                          ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
    return await foo(), await x;
                        ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
    return await foo() + await x;
}
async function handleConditionalExpression() {
    return await foo() ? await x : await x;
                         ~~~~~              [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
                                   ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
}

throw await x;
await x;
return await x;
       ~~~~~    [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]

try {
    (async () => await x)();
                 ~~~~~       [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
} catch {
    return await foo();
           ~~~~~        [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
}

async () => await {foo: 1};
            ~~~~~           [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]

async function parensWhenNecessary() {
    return await {foo: 1};
           ~~~~~           [error no-return-await: Awaiting the returned value is redundant as it is wrapped in a Promise anyway.]
}
