export {};
declare let x: Promise<string>;
function notAsync() {
    return;
    return x;
    try {
        return x;
    } catch {
        return x;
    } finally {
        return x;
    }
}
async function test() {
    return x;
    try {
        return;
        return x;
        ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        function nested() {
            return x;
        }
        return await x;
        return (x);
        ~~~~~~      [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return (
            await x
        );
        return {
            fn() {
                return x;
            },
            get x() {
                return x;
            },
            async asyncFn() {
                return x;
            },
        };
        return await x || x;
        ~~~~~~               [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return x || await x;
        ~~~~~~               [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return (x || await x);
        ~~~~~~                 [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return x && await x;
        return Boolean() ? x : x;
        ~~~~~~                    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return(Boolean() ? await x : x);
        ~~~~~~                           [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return Boolean() ? x : await x;
        ~~~~~~                          [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        {
            for (;;) {
                return x;
                ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
            }
        }
    } catch {
        return x;
        ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
    } finally {
        return x;
    }
    try {
        return x;
        ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
    } finally {
        return x;
    }
    try {
        return x;
        ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        try {
            return x;
            ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        } catch {
            return x;
            ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        }
        return x;
        ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        try {
            return x;
            ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        } finally {
            return x;
            ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        }
        return x;
        ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
    } catch {
        return x;
        try {
            return x;
            ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        } catch {
            return x;
        }
        return x;
    }
    function nested() {
        try {
            return x;
        } catch {
            return x;
        }
    }
}
