export {};
declare function get<T>(): T;
interface MyWeirdPromise<V> {
    then<T extends (p: V) => void>(cb: T): void;
}
interface MyEvenWeirderPromise<T> {
    then(cb: T): void;
}
async function test<T extends PromiseLike<string>, U extends {then(cb: () => void): void}>(p1: T, p2: U) {
    try {
        let x: T | U | boolean = null as any;
        return x;
        ~~~~~~    [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return p1;
        ~~~~~~     [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return p2;
        ~~~~~~     [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<Promise<void>>();
        ~~~~~~                       [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<void>>();
        ~~~~~~                           [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<MyWeirdPromise<string>>();
        ~~~~~~                                [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<MyEvenWeirderPromise<(v: string) => void>>();
        ~~~~~~                                                   [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<Record<'then', (cb: (v: string) => void) => void>>();
        ~~~~~~                                                           [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<Pick<PromiseLike<string>, 'then'>>();
        ~~~~~~                                           [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<Promise<string> | string>();
        ~~~~~~                                  [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{} | Promise<string> | string>();
        ~~~~~~                                       [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<void> | Promise<void>>();
        ~~~~~~                                           [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<string> | PromiseLike<number>>();
        ~~~~~~                                                   [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<Promise<string> | PromiseLike<number>>();
        ~~~~~~                                               [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<(Promise<string> | PromiseLike<number>) & {foo: any}>();
        ~~~~~~                                                              [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then(): void, then(cb: (v: string) => void): void}>();
        ~~~~~~                                                             [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then: {(): void, (cb: (v: string) => void): void}}>();
        ~~~~~~                                                             [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then(...args: Array<() => void>): void}>();
        ~~~~~~                                                  [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then(cb: () => void): void}>();
        ~~~~~~                                      [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then(cb: (v: string) => void): void}>();
        ~~~~~~                                               [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then(cb?: (v: string) => void): void}>();
        ~~~~~~                                                [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then(fulfill: (v: string) => void, reject: (v: string) => void): void}>();
        ~~~~~~                                                                                 [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<{then(fulfill: () => void, reject: () => void, something: () => void): void}>();
        ~~~~~~                                                                                      [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<number> | {then(fulfill: (v: string) => void, reject: (v: string) => void): void}>();
        ~~~~~~                                                                                                       [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<number> | {then(fulfill: (v: string, v2: number) => void): void}>();
        ~~~~~~                                                                                      [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<number> & {then: {}}>();
        ~~~~~~                                          [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<number> & {then(): void}>();
        ~~~~~~                                              [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        return get<PromiseLike<number> & {then(cb: (v: number) => void): void}>();
        ~~~~~~                                                                     [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]
        // the compiler complains when adding `await` here because the signatures are not compatible
        // adding a check for this case is not worth the effort because the compiler also won't let you return this abomination
        return get<PromiseLike<number> & {then(cb: () => void): void}>();
        ~~~~~~                                                            [error try-catch-return-await: Missing 'await' of Promise returned inside try-catch.]

        // not valid Promises
        return get<{then: any}>();
        return get<{then(): void}>();
        return get<{}>();
        return get<any>();
        return get<{[key: string]: any}>();
        return get<{[key: string]: (cb: (v: any) => void) => void}>();
        return get<{then(fulfill: string): void}>();
        return get<{then(...args: () => void): void}>();
        return get<string | number>();
    } catch {
    }
}
